#!/usr/bin/env python

from __future__ import print_function
from z3 import *

def validate_sign_by_shift():
  """
  sign = v >> (sizeof(int) * CHAR_BIT - 1);
  """
  v = BitVec("v", 32)
  s = v >> 31
  print("Validating sign trick:")
  prove(
    Or(
      And(v < 0, s == -1),
      And(v >= 0, s == 0),
    )
  )

def validate_opposite_sign_by_xor():
  """
  int x, y;               // input values to compare signs
  bool f = ((x ^ y) < 0); // true iff x and y have opposite signs
  """
  x = BitVec("x", 32)
  y = BitVec("y", 32)
  f = (x^y) < 0

  print("Validating sign trick:")
  prove(
    Or(
      And(x >= 0, y >= 0, f == False),
      And(x < 0, y < 0, f == False),
      And(x >= 0, y < 0, f == True),
      And(x < 0, y >= 0, f == True),
    )
  )



validate_sign_by_shift()
validate_opposite_sign_by_xor()


"""
Based on https://graphics.stanford.edu/~seander/bithacks.html
"""
