#!/usr/bin/env python


from __future__ import print_function
import z3

class Bridges:
  def __init__(self, data):
    data = [line.split() for line in data.split("\n")]
    data = [line for line in data if line != []]
    data = [[None if c == "_" else int(c) for c in line] for line in data]
    self.xsize = len(data[0])
    self.ysize = len(data)
    self.data = {(x,y): data[y][x] for x in range(self.xsize) for y in range(self.ysize)}
    self.solver = z3.Solver()

  def print_answer(self):
    pass

  def solve(self):
    # Setup constraints

    if self.solver.check() == z3.sat:
      self.model = self.solver.model()
      self.print_answer()
    else:
      print("failed to solve")


bridges = Bridges(
"""
3 _ _ 6 _ _ 4
_ 1 _ _ _ _ _
_ _ _ 4 _ 4 _
_ _ _ _ _ _ _
_ _ 1 _ 3 _ _
1 _ _ _ _ 2 _
_ 3 _ _ 5 _ 3
"""
)
bridges.solve()
