#!/usr/bin/env python

from __future__ import print_function
import z3

class LightUp:
  def __init__(self, data):
    data = [line for line in data.split("\n") if line != ""]
    data = [[c for c in line] for line in data]
    self.xsize = len(data[0])
    self.ysize = len(data)
    self.data  = {(x,y): data[y][x] for x in range(self.xsize) for y in range(self.ysize)}
    self.solver = z3.Solver()

  def print_answer(self):
    for y in range(self.ysize):
      for x in range(self.xsize):
        if self.data[x,y] != ".":
          print(self.data[x,y], end="")
        else:
          print("?", end="")
      print("")

  def solve(self):
    # setup variables ...


    if self.solver.check() == z3.sat:
      self.model = self.solver.model()
      self.print_answer()
    else:
      print("failed to solve")




LightUp(
"""
....0..
.......
x.2.x..
...3...
..x.x.3
.......
..1....
"""
).solve()
