#!/usr/bin/env python

from __future__ import print_function
from z3 import *

def problem_01():
  """
  An airplane accelerates down a runway at 3.20 m/s2 for 32.8 s until is finally lifts off the ground.
  Determine the distance traveled before takeoff.
  """
  s = Solver()
  a = Real("a")
  t = Real("t")
  d = Real("d")

  s.add(a == 3.20)
  s.add(t == 32.8)
  s.add(d == a*t*t/2)

  if s.check() == sat:
    print(s.model())
  else:
    print("No solution")

def problem_02():
  """
  A car starts from rest and accelerates uniformly over a time of 5.21 seconds for a distance of 110 m. Determine the acceleration of the car.
  """
  s = Solver()
  a = Real("a")
  t = Real("t")
  d = Real("d")

  s.add(d == a*t*t/2)
  s.add(t == 5.21)
  s.add(d == 110)

  if s.check() == sat:
    print(s.model())
  else:
    print("No solution")


problem_01()
problem_02()


"""
http://www.physicsclassroom.com/class/1DKin/Lesson-6/Sample-Problems-and-Solutions
"""
